import { HardhatUserConfig } from "hardhat/config";
import { HardhatConfig } from "hardhat/types/config";
import { HardhatUserConfigValidationError } from "hardhat/types/hooks";

import { CoreMockConfig } from "./types.js";

// Hardcoded address where the HelloWorld core contract will be deployed
export const CORE_CONTRACT_ADDRESS =
  "0x0000000000000000000000000000000000000042";

/**
 * This function validates the parts of the HardhatUserConfig that are relevant
 * to the plugin.
 *
 * This function is called from the `validateUserConfig` Hook Handler.
 *
 * @param userConfig The HardhatUserConfig, as exported in the config file.
 * @returns An array of validation errors, or an empty array if valid.
 */
export async function validatePluginConfig(
  userConfig: HardhatUserConfig,
): Promise<HardhatUserConfigValidationError[]> {
  if (userConfig.coreMock === undefined) {
    return [];
  }

  if (typeof userConfig.coreMock !== "object") {
    return [
      {
        path: ["coreMock"],
        message: "Expected an object with core mock settings.",
      },
    ];
  }

  const errors: HardhatUserConfigValidationError[] = [];
  const settings = userConfig.coreMock;

  if (
    settings.enabled !== undefined &&
    typeof settings.enabled !== "boolean"
  ) {
    errors.push({
      path: ["coreMock", "enabled"],
      message: "Expected a boolean.",
    });
  }

  return errors;
}

/**
 * Resolves the plugin config, based on an already validated HardhatUserConfig
 * and a partially resolved HardhatConfig.
 *
 * This function is called from the `resolveUserConfig` Hook Handler.
 *
 * @param userConfig The HardhatUserConfig.
 * @param partiallyResolvedConfig The partially resolved HardhatConfig, which is
 *  generated by calling `next` in the `resolveUserConfig` Hook Handler.
 * @returns The resolved HardhatConfig.
 */
export async function resolvePluginConfig(
  userConfig: HardhatUserConfig,
  partiallyResolvedConfig: HardhatConfig,
): Promise<HardhatConfig> {
  const userSettings = (userConfig.coreMock ?? {});
  const coreMock: CoreMockConfig = {
    enabled: userSettings.enabled ?? true,
  };

  return {
    ...partiallyResolvedConfig,
    coreMock,
  };
}
