import { strict as assert } from "node:assert";
import { describe, it } from "node:test";
import { network } from "hardhat";
import { nox } from "@iexec-nox/nox-hardhat-plugin";

describe("nox API", () => {
  it("connect() returns pre-configured handle operations", async () => {
    const connection = await network.getOrCreate();
    const conn = await nox.connect(connection);
    assert.equal(typeof conn.publicDecrypt, "function");
    assert.equal(typeof conn.encryptInput, "function");
    assert.equal(typeof conn.decrypt, "function");
  });

  it("encryptInput() returns a { handle, handleProof } pair", async () => {
    const connection = await network.getOrCreate();
    const { encryptInput } = await nox.connect(connection);
    const result = await encryptInput(
      42n,
      "uint256",
      "0x000000000000000000000000000000000000dead",
    );
    assert.match(
      result.handle,
      /^0x[0-9a-fA-F]{64}$/,
      "handle should be a 32-byte hex string",
    );
    assert.match(
      result.handleProof,
      /^0x[0-9a-fA-F]+$/,
      "handleProof should be a hex string",
    );
  });

  it("publicDecrypt() returns the cleartext of a publicly decryptable handle", async () => {
    const connection = await network.getOrCreate();
    const { publicDecrypt } = await nox.connect(connection);
    const token = await connection.viem.deployContract("MyConfidentialToken", [
      "Nox API Token",
      "NAT",
      "ipfs://example",
      7n,
    ]);
    const handle =
      (await token.read.confidentialTotalSupply()) as `0x${string}`;
    const { value } = await publicDecrypt(handle);
    assert.equal(value, 7n);
  });
});

describe("nox.connect() with a non-default account", () => {
  it(
    "binds encryptInput/decrypt to the requested account instead of account[0]",
    { timeout: 120_000 },
    async () => {
      const connection = await network.getOrCreate();
      const [owner, depositor] = await connection.viem.getWalletClients();

      const ownerConn = await nox.connect(connection);
      const depositorConn = await nox.connect(
        connection,
        depositor.account.address,
      );

      const token = await connection.viem.deployContract(
        "MyConfidentialToken",
        ["Nox Account Token", "NAT", "ipfs://example", 100n],
      );

      const TRANSFER_AMOUNT = 30n;

      // A handle generated by `depositor` can't be used by `owner`.
      const { handle: foreignHandle, handleProof: foreignProof } =
        await depositorConn.encryptInput(
          TRANSFER_AMOUNT,
          "uint256",
          token.address,
        );
      await assert.rejects(() =>
        token.write.confidentialTransfer(
          [depositor.account.address, foreignHandle, foreignProof],
          { account: owner.account },
        ),
      );

      // The matching proof, encrypted for `owner`, lets `owner` transfer to `depositor`.
      const { handle, handleProof } = await ownerConn.encryptInput(
        TRANSFER_AMOUNT,
        "uint256",
        token.address,
      );
      await token.write.confidentialTransfer(
        [depositor.account.address, handle, handleProof],
        { account: owner.account },
      );

      const depositorBalanceHandle = (await token.read.confidentialBalanceOf([
        depositor.account.address,
      ])) as `0x${string}`;

      // `depositorConn.decrypt()` signs as `depositor` authorized to view it's balance.
      const { value } = await depositorConn.decrypt(depositorBalanceHandle);
      assert.equal(value, TRANSFER_AMOUNT);

      // `ownerConn.decrypt()` signs as `owner` not authorized to view `depositor`'s balance.
      await assert.rejects(
        () => ownerConn.decrypt(depositorBalanceHandle),
        /not authorized to decrypt it/,
      );
    },
  );
});
