name: Conventional Commits - Lint PR Title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened

jobs:
  lint-pr-title:
    permissions:
      pull-requests: read
    uses: iExecBlockchainComputing/github-actions-workflows/.github/workflows/conventional-commits.yml@687421dcd8ff445567999c199908559282f8ff40 # conventional-commits-v1.0.1
